//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDbTelefonRehberi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler
    {
        public int KisiId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Telefonu { get; set; }
        public Nullable<bool> aktifMi { get; set; }
    }
}
